### ISSUE TITLE
it no work no more

### ISSUE THREAD

**Issue by iiAlanii** [4ngel2769/discord-rpc#1]
it no work no more sir

**Comment by Zone-Infinity** [comment]
Discord deprecated their API for doing this.
They want us to use their [Game SDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide)

**Comment by 4ngel2769** [comment]
I'll get to working on an easier way of doing this (for the moment it will only be functional on Windows).
This repository will be archived.
